import Head from "next/head";
import { Inter } from "next/font/google"
import { NextPage } from "next";

const inter = Inter({ subsets: ["latin"] });

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione inventore repellat deserunt doloremque aliquid neque perspiciatis reiciendis temporibus, iste maxime natus distinctio, tenetur delectus veniam, similique expedita? At, velit nam.
        </p>
      </main>
    </>
  )
}

export default Home